# Generated by Django 4.0.1 on 2022-02-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
