# Generated by Django 4.0.1 on 2022-02-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=250)),
            ],
        ),
    ]
