# Generated by Django 4.0.1 on 2022-02-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_product_name_products_productname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='productname',
            new_name='product_name',
        ),
    ]
