# Generated by Django 4.0.1 on 2022-02-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_order_customer_order_product_subcategories_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCategories',
            new_name='SubCat',
        ),
    ]
