# Generated by Django 4.0.1 on 2022-02-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_subcategories_subcat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCat',
            new_name='SubCategories',
        ),
    ]
