# Generated by Django 4.0.1 on 2022-02-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='imagename',
            field=models.CharField(default='', max_length=250),
        ),
    ]
