# Generated by Django 4.0.1 on 2022-02-08 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_product_image_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('aprice', models.CharField(max_length=100)),
                ('dprice', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='shop/img')),
                ('shortdesc', models.TextField()),
                ('longdesc', models.TextField()),
                ('Brand', models.CharField(max_length=150)),
                ('quant', models.IntegerField()),
                ('date', models.DateField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.categories')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.subcategories')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product'),
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
