# Generated by Django 4.0.1 on 2022-03-25 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0023_alter_product_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='Zip',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='fullname',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
